### ISSUE TITLE
How to add more reports to the dashboard?

### ISSUE THREAD

**Issue by raghukovvuru** [joelios/libraDash#1]
Hello Team, 

                This is very clean and useful dashboard apps available for ERPNext. Need some small help from you, can we add more reports like purchase orders, production orders, Total sales, Total purchases same like the Sales?

**Comment by joelios** [comment]
hi @raghubuilds 
sure...what kind of help do you need?

**Comment by joelios** [comment]
I will bring a new better version out in a few days
